#!/bin/bash

set -e

DIR=$(realpath "$(dirname "$0")/../")
BACKUP_DIR=$DIR/backup

mkdir -p "$BACKUP_DIR"

cd "$DIR"
for file in *; do
  # ATENCION: cualquier archivo que no matchee esta exclusion se va a
  # copiar como symlink al home de todos los usuarios al correr el install.
  [[ "$file" =~ (ssh|script|backup|README.*md|.*sample$|.*\.sh$) ]] && continue
  if [ -e "$HOME/.$file" ] && [ ! -L "$HOME/.$file" ]; then
    mv "$HOME/.$file" "$BACKUP_DIR"
    echo "⚠️  ~/.${file} existente respaldado en $BACKUP_DIR/$file"
    echo "    Revisa el backup y migra lo que necesites manualmente."
  fi
  ln -fs "$DIR/$file" "$HOME/.$file"
done

mkdir -p $HOME/.ssh/config.d
[ -e "$HOME/.ssh/config" ] && [ ! -L "$HOME/.ssh/config" ] && \
  mkdir -p "$BACKUP_DIR/.ssh" && \
  mv "$HOME/.ssh/config" "$BACKUP_DIR/.ssh/config"
mkdir -p "$HOME/.ssh"
ln -fs "$DIR/ssh/config" "$HOME/.ssh/config"

# Install vim-plug as autoload
curl -sfLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Install vim spell check es
for i in es.latin1.spl es.latin1.sug es.utf-8.spl es.utf-8.sug; do
  curl -sfLo "$HOME/.vim/spell/$i" --create-dirs \
    "https://ftp.nluug.nl/pub/vim/runtime/spell/$i"
done
# Install vim plugins
vim +PlugClean +PlugUpdate +qall
